spring:
  datasource:
    username: csit
    password: csit@test123
    url: jdbc:mysql://39.108.188.30:3566/sys?characterEncoding=utf-8&useSSL=false&autoReconnect=true&amp;failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080